/**
 * Read-only Academy audio primitives.
 *
 * Narration generation is deliberately absent from the web application.
 * Versioned assets can only be generated by the explicit, isolated
 * scripts/generate-final-piper-academy.ts administrative CLI.
 */
export {
  AUDIO_ENGINE,
  audioTextHash,
  parseRange,
} from "./narration-core";
