"use client";

import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { Pause, Play, Square } from "lucide-react";
import { AUDIO_SECOND_EVENT } from "@/components/academy/telemetry-beacon";
import {
  useAcademyFollowAlong,
  type AcademyFollowAlongCue,
} from "@/components/academy/follow-along-context";
import type { AcademyAudioResumeSnapshot } from "@/lib/academy/resume-server";
import {
  useAcademyResumeSaver,
  type AcademyAudioResumePosition,
} from "@/lib/academy/resume-client";
import {
  clearAcademyAudioResumeShadow,
  readAcademyAudioResumeShadow,
  selectFreshestAcademyAudioResume,
  writeAcademyAudioResumeShadow,
} from "@/lib/academy/audio-resume-shadow";

/**
 * Lesson narration player. Audited narration releases are generated by an
 * isolated administrative batch and served as plain MP3s, so every device and
 * browser gets the same approved production narration and controls that work:
 *  - Voice changes apply mid-playback: the player swaps the source and
 *    resumes at the same fraction of the narration, still inside the user's
 *    gesture (which keeps iOS happy).
 *  - Speed is the audio element's playbackRate: instant everywhere.
 *  - Seeking works because the server honors HTTP Range requests.
 *
 * If the active narration is unavailable, the player reports that state and
 * retries the approved source. It never substitutes an unapproved device
 * voice, which keeps both the one-voice experience and durable timestamps
 * honest.
 */

type VoiceStatus = {
  id: string;
  label: string;
  tagline: string;
  ready: boolean;
  durationSeconds: number | null;
  resumeKey: string | null;
};

type NarrationStatus = {
  narration: boolean;
  defaultVoice: string | null;
  productionVoiceLocked?: boolean;
  releaseMode?: "legacy" | "versioned";
  activeRelease?: {
    id: string;
    recipeVersion: string;
    recipeHash: string;
    voiceId: string;
    sourceContentManifestHash: string;
  } | null;
  followAlong?: {
    resumeKey: string;
    trackUrl: string;
    cueCount: number;
    manifestHash: string;
  } | null;
  voices: VoiceStatus[];
};

const RATES = [0.75, 1, 1.25, 1.5];
const VOICE_PREF_KEY = "txp-narration-voice";
const RATE_PREF_KEY = "txp-narration-rate";
const ACTIVE_RELEASE_PREF_MIGRATION_KEY =
  "txp-narration-active-release-preferences-v1";
const MAX_MEDIA_RETRY_ATTEMPTS = 5;
const RESUME_RECONCILE_TIMEOUT_MS = 4_000;

function formatTime(totalSeconds: number): string {
  const s = Math.max(0, Math.floor(totalSeconds));
  const m = Math.floor(s / 60);
  return `${m}:${String(s % 60).padStart(2, "0")}`;
}

function parseFollowAlongCue(
  cue: TextTrackCue | null,
): AcademyFollowAlongCue | null {
  if (!cue || !("text" in cue)) return null;
  let value: unknown;
  try {
    value = JSON.parse((cue as VTTCue).text);
  } catch {
    return null;
  }
  if (
    typeof value !== "object" ||
    value === null ||
    Array.isArray(value)
  ) {
    return null;
  }
  const record = value as Record<string, unknown>;
  if (
    !Number.isInteger(record.blockIndex) ||
    typeof record.semanticBlockId !== "string" ||
    !/^[a-f0-9]{64}$/u.test(record.semanticBlockId) ||
    typeof record.sourceHtmlPath !== "string" ||
    record.sourceHtmlPath.length === 0 ||
    record.sourceHtmlPath.length > 512 ||
    !Number.isFinite(cue.startTime) ||
    !Number.isFinite(cue.endTime) ||
    cue.endTime <= cue.startTime
  ) {
    return null;
  }
  return {
    blockIndex: record.blockIndex as number,
    semanticBlockId: record.semanticBlockId,
    sourceHtmlPath: record.sourceHtmlPath,
    startMs: Math.round(cue.startTime * 1_000),
    endMs: Math.round(cue.endTime * 1_000),
  };
}

function AudioUnavailable({
  note,
  onRetry,
}: {
  note: string;
  onRetry: () => void;
}) {
  return (
    <div className="min-h-[7.75rem] space-y-2 rounded-md border border-neutral-200 bg-neutral-50 p-3">
      <div className="flex flex-wrap items-center gap-3">
        <span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Listen</span>
        <button type="button" onClick={onRetry} className="inline-flex h-9 items-center rounded-md border border-neutral-300 bg-white px-3 text-sm font-medium text-navy-900 hover:bg-neutral-50">
          Retry studio audio
        </button>
      </div>
      <p className="text-xs text-slate-500">{note}</p>
    </div>
  );
}

/* ------------------------------------------------------------------------ */
/* Primary: server narration through a plain audio element.                 */
/* ------------------------------------------------------------------------ */

export function AudioReader({
  slug,
  title,
  resume,
  resumeEndpoint,
  resumeShadowScope,
  resumeEnabled = true,
}: {
  slug: string;
  title?: string;
  resume: AcademyAudioResumeSnapshot;
  resumeEndpoint: string;
  resumeShadowScope: string | null;
  resumeEnabled?: boolean;
}) {
  const {
    activeCue,
    mode: followMode,
    requestShowActive,
    setActiveCue,
    setAvailable: setFollowAlongAvailable,
    setPlaying: setFollowAlongPlaying,
    toggleFollow,
  } = useAcademyFollowAlong();
  const [status, setStatus] = useState<NarrationStatus | null>(null);
  const [statusFailed, setStatusFailed] = useState(false);
  const [voiceId, setVoiceId] = useState<string | null>(null);
  const [rate, setRate] = useState(1);
  const [playing, setPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [followTrackReady, setFollowTrackReady] =
    useState(false);
  const [serverResume, setServerResume] =
    useState<AcademyAudioResumeSnapshot>(resume);
  const [resumeReconciled, setResumeReconciled] =
    useState(!resumeEnabled);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const trackRef = useRef<HTMLTrackElement | null>(null);
  const followCueEnabledRef = useRef(false);
  // Where to resume (as a fraction of duration) after a mid-playback voice swap.
  const pendingSeekFractionRef = useRef<number | null>(null);
  // A durable saved time uses absolute seconds because the resume key binds it
  // to one immutable asset. It is applied only after media metadata is ready.
  const pendingInitialSeekSecondsRef = useRef<number | null>(null);
  const initialResumeHandledRef = useRef(false);
  const allowAudioSaveRef = useRef(false);
  const lastTimedSaveAtRef = useRef(0);
  const lastShadowSaveAtRef = useRef(0);
  const loadedResumeKeyRef = useRef<string | null>(null);
  const appliedMediaReloadRef = useRef(0);
  const mediaRetryTimerRef = useRef<number | null>(null);
  const mediaRetryAttemptRef = useRef(0);
  const mediaRetrySourceKeyRef = useRef<string | null>(null);
  const mediaPlaybackStartedAtRef = useRef<number | null>(null);
  const statusRequestGenerationRef = useRef(0);
  const statusRequestRef =
    useRef<Promise<NarrationStatus | null> | null>(null);
  const statusAbortRef = useRef<AbortController | null>(null);
  const rateRef = useRef(1);
  const [mediaReload, setMediaReload] = useState(0);
  const [mediaRetryExhausted, setMediaRetryExhausted] =
    useState(false);

  const refreshStatus = useCallback(() => {
    if (statusRequestRef.current) {
      return statusRequestRef.current;
    }
    const requestGeneration =
      ++statusRequestGenerationRef.current;
    const controller = new AbortController();
    statusAbortRef.current = controller;
    const timeout = window.setTimeout(() => {
      controller.abort();
    }, 10_000);
    const request = (async () => {
      try {
        const res = await fetch(`/api/partner/academy/audio/${encodeURIComponent(slug)}`, {
          cache: "no-store",
          signal: controller.signal,
        });
        if (!res.ok) throw new Error(String(res.status));
        const body = (await res.json()) as NarrationStatus;
        if (
          requestGeneration !==
          statusRequestGenerationRef.current
        ) {
          return null;
        }
        setStatus(body);
        setStatusFailed(false);
        return body;
      } catch {
        if (
          requestGeneration !==
          statusRequestGenerationRef.current
        ) {
          return null;
        }
        setStatusFailed(true);
        return null;
      } finally {
        window.clearTimeout(timeout);
        if (statusAbortRef.current === controller) {
          statusAbortRef.current = null;
        }
      }
    })();
    statusRequestRef.current = request;
    void request.then(() => {
      if (statusRequestRef.current === request) {
        statusRequestRef.current = null;
      }
    });
    return request;
  }, [slug]);

  useEffect(
    () => () => {
      statusRequestGenerationRef.current += 1;
      statusAbortRef.current?.abort();
      statusAbortRef.current = null;
      statusRequestRef.current = null;
    },
    [slug],
  );

  const saveResume = useAcademyResumeSaver({
    endpoint: resumeEndpoint,
    initialRevision: serverResume.revision,
    enabled: resumeEnabled,
    onSourceInvalidated: () => {
      void refreshStatus();
    },
  });

  // A page refresh can start its server render before the old document's
  // keepalive POST commits. Re-read once after hydration, when that write has
  // had time to settle. The synchronous local shadow below closes the same
  // race even when this request is slow or storage on the server is briefly
  // unavailable.
  useEffect(() => {
    setServerResume(resume);
    if (!resumeEnabled) {
      setResumeReconciled(true);
      return;
    }
    let cancelled = false;
    let controller: AbortController | null = null;
    let requestTimeout: number | null = null;
    setResumeReconciled(false);
    const reconcile = async () => {
      await new Promise<void>((resolve) => {
        window.setTimeout(resolve, 120);
      });
      if (cancelled) return;
      const requestController = new AbortController();
      controller = requestController;
      requestTimeout = window.setTimeout(
        () => requestController.abort(),
        RESUME_RECONCILE_TIMEOUT_MS,
      );
      const sentAt = Date.now();
      try {
        const response = await fetch(resumeEndpoint, {
          credentials: "same-origin",
          cache: "no-store",
          signal: requestController.signal,
        });
        if (response.ok) {
          const body = (await response.json()) as {
            audio?: AcademyAudioResumeSnapshot;
            serverNow?: unknown;
          };
          if (
            !cancelled &&
            body.audio &&
            typeof body.audio.revision === "number"
          ) {
            const receivedAt = Date.now();
            const serverNow =
              typeof body.serverNow === "number" &&
              Number.isSafeInteger(body.serverNow) &&
              body.serverNow >= 0
                ? body.serverNow
                : null;
            const serverUpdatedAt =
              body.audio.updatedAt;
            setServerResume({
              ...body.audio,
              updatedAt:
                serverNow !== null &&
                typeof serverUpdatedAt === "number" &&
                Number.isSafeInteger(serverUpdatedAt) &&
                serverUpdatedAt >= 0
                  ? Math.max(
                      0,
                      Math.round(
                        serverUpdatedAt +
                          (sentAt + receivedAt) / 2 -
                          serverNow,
                      ),
                    )
                  : serverUpdatedAt,
            });
          }
        }
      } catch {
        // The validated local shadow still provides exact same-browser resume.
      } finally {
        if (requestTimeout !== null) {
          window.clearTimeout(requestTimeout);
          requestTimeout = null;
        }
        if (!cancelled) setResumeReconciled(true);
      }
    };
    void reconcile();
    return () => {
      cancelled = true;
      controller?.abort();
      if (requestTimeout !== null) {
        window.clearTimeout(requestTimeout);
      }
    };
  }, [resume, resumeEnabled, resumeEndpoint]);

  // Initial status, restore saved preferences.
  useEffect(() => {
    try {
      const savedRate = Number(window.localStorage.getItem(RATE_PREF_KEY));
      if (RATES.includes(savedRate)) {
        setRate(savedRate);
        rateRef.current = savedRate;
      }
    } catch {
      /* storage unavailable */
    }
    void refreshStatus();
  }, [refreshStatus]);

  // The first active-release visit safely migrates legacy preferences. The
  // marker is written even when the old speed was not 1.5x, so a user may
  // deliberately choose 1.5x later without it being reset on the next visit.
  useEffect(() => {
    if (!status?.productionVoiceLocked) return;
    const activeVoiceId =
      status.defaultVoice ??
      status.voices.find((voice) => voice.ready)?.id;
    if (!activeVoiceId) return;
    setVoiceId(activeVoiceId);
    try {
      window.localStorage.setItem(
        VOICE_PREF_KEY,
        activeVoiceId,
      );
      if (
        !window.localStorage.getItem(
          ACTIVE_RELEASE_PREF_MIGRATION_KEY,
        )
      ) {
        if (
          Number(
            window.localStorage.getItem(
              RATE_PREF_KEY,
            ),
          ) === 1.5
        ) {
          window.localStorage.setItem(RATE_PREF_KEY, "1");
          setRate(1);
          rateRef.current = 1;
          if (audioRef.current) {
            audioRef.current.playbackRate = 1;
          }
        }
        window.localStorage.setItem(
          ACTIVE_RELEASE_PREF_MIGRATION_KEY,
          status.activeRelease?.id ?? "active",
        );
      }
    } catch {
      /* storage unavailable */
    }
  }, [
    status?.productionVoiceLocked,
    status?.defaultVoice,
    status?.voices,
    status?.activeRelease?.id,
  ]);

  // Pick the voice once the status is known: saved preference if ready,
  // otherwise the configured default, otherwise the first ready voice.
  useEffect(() => {
    if (!status || voiceId) return;
    let saved: string | null = null;
    try {
      saved = window.localStorage.getItem(VOICE_PREF_KEY);
    } catch {
      /* storage unavailable */
    }
    const ready = status.voices.filter((v) => v.ready);
    const pick =
      ready.find((v) => v.id === saved)?.id ??
      ready.find((v) => v.id === status.defaultVoice)?.id ??
      ready[0]?.id ??
      status.defaultVoice;
    if (pick) setVoiceId(pick);
  }, [status, voiceId]);

  // Poll whenever the read-only status reports missing/stale narration. This
  // never starts generation; it only lets a newly activated audited asset
  // replace the temporary device fallback without requiring a page reload.
  const selected = useMemo(
    () => status?.voices.find((v) => v.id === voiceId) ?? null,
    [status, voiceId],
  );
  const followAlong =
    status?.followAlong &&
    selected?.resumeKey === status.followAlong.resumeKey
      ? status.followAlong
      : null;
  const resumePending =
    resumeEnabled && !resumeReconciled;

  const syncActiveTrackCue = useCallback(() => {
    if (!followCueEnabledRef.current) {
      setActiveCue(null);
      return;
    }
    const track = trackRef.current?.track;
    if (!track) return;
    let cue: TextTrackCue | null = null;
    // Treat media currentTime and the audited loaded cue list as authoritative.
    // WebKit can briefly retain a non-empty but stale activeCues list after a
    // paused seek, which would otherwise highlight the previous passage.
    if (track.cues && audioRef.current) {
      const time = audioRef.current.currentTime;
      for (
        let index = 0;
        index < track.cues.length;
        index += 1
      ) {
        const candidate = track.cues[index];
        if (
          candidate.startTime <= time &&
          time < candidate.endTime
        ) {
          cue = candidate;
          break;
        }
      }
    } else if (
      track.activeCues &&
      track.activeCues.length > 0
    ) {
      cue = track.activeCues[0];
    }
    setActiveCue(parseFollowAlongCue(cue));
  }, [setActiveCue]);

  useEffect(() => {
    setFollowTrackReady(false);
    setFollowAlongAvailable(false);
    if (!followAlong || mediaRetryExhausted) {
      setFollowAlongPlaying(false);
      setActiveCue(null);
      return;
    }
    const element = trackRef.current;
    if (!element) return;
    const track = element.track;
    track.mode = "hidden";
    const onCueChange = () => syncActiveTrackCue();
    const clearTrack = () => {
      setFollowTrackReady(false);
      setFollowAlongAvailable(false);
      setActiveCue(null);
    };
    const onTrackLoad = () => {
      const cues = track.cues;
      if (
        element.readyState !== 2 ||
        !cues ||
        cues.length !== followAlong.cueCount
      ) {
        clearTrack();
        return;
      }
      for (let index = 0; index < cues.length; index += 1) {
        if (!parseFollowAlongCue(cues[index])) {
          clearTrack();
          return;
        }
      }
      setFollowTrackReady(true);
      setFollowAlongAvailable(true);
      syncActiveTrackCue();
    };
    track.addEventListener("cuechange", onCueChange);
    element.addEventListener("load", onTrackLoad);
    element.addEventListener("error", clearTrack);
    if (element.readyState === 2) {
      onTrackLoad();
    }
    return () => {
      track.removeEventListener("cuechange", onCueChange);
      element.removeEventListener("load", onTrackLoad);
      element.removeEventListener("error", clearTrack);
      clearTrack();
    };
  }, [
    followAlong,
    mediaRetryExhausted,
    setActiveCue,
    setFollowAlongAvailable,
    setFollowAlongPlaying,
    syncActiveTrackCue,
  ]);

  useEffect(
    () => () => {
      setFollowAlongAvailable(false);
      setFollowAlongPlaying(false);
      setActiveCue(null);
    },
    [
      setActiveCue,
      setFollowAlongAvailable,
      setFollowAlongPlaying,
    ],
  );
  useEffect(() => {
    const sourceKey = selected?.resumeKey ?? null;
    if (
      !sourceKey ||
      mediaRetrySourceKeyRef.current === sourceKey
    ) {
      return;
    }
    mediaRetrySourceKeyRef.current = sourceKey;
    mediaRetryAttemptRef.current = 0;
    mediaPlaybackStartedAtRef.current = null;
    setMediaRetryExhausted(false);
    if (mediaRetryTimerRef.current !== null) {
      window.clearTimeout(mediaRetryTimerRef.current);
      mediaRetryTimerRef.current = null;
    }
  }, [selected?.resumeKey]);
  const anyNotReady = Boolean(status?.voices.some((v) => !v.ready));
  useEffect(() => {
    if (
      !status ||
      (status.narration &&
        status.voices.length > 0 &&
        !anyNotReady)
    ) {
      return;
    }
    const id = window.setInterval(() => {
      void refreshStatus();
    }, 5000);
    return () => window.clearInterval(id);
  }, [
    status,
    status?.narration,
    status?.voices.length,
    anyNotReady,
    refreshStatus,
  ]);

  // A failed status fetch must never be terminal: keep retrying quietly so a
  // transient blip or server restart cannot lock the session into the device
  // voice fallback.
  useEffect(() => {
    if (!statusFailed) return;
    const id = window.setInterval(() => {
      void refreshStatus();
    }, 10000);
    return () => window.clearInterval(id);
  }, [statusFailed, refreshStatus]);

  // Engagement telemetry: one event per second of actual playback, the same
  // event the beacon already aggregates.
  useEffect(() => {
    if (!playing) return;
    const id = window.setInterval(() => {
      window.dispatchEvent(new CustomEvent(AUDIO_SECOND_EVENT));
    }, 1000);
    return () => window.clearInterval(id);
  }, [playing]);

  const srcFor = useCallback(
    (v: string) => `/api/partner/academy/audio/${encodeURIComponent(slug)}/${encodeURIComponent(v)}`,
    [slug],
  );

  // The audio element's src is set IMPERATIVELY, never as a React prop: a
  // controlled src prop would be re-committed after changeVoice's in-gesture
  // swap, re-running the media load algorithm and aborting the just-issued
  // play(). This effect only covers mount and the ready transition; it
  // compares the attribute first so it never disturbs an element changeVoice
  // has already pointed at the right source. The immutable resume key is also
  // part of the identity: a new release commonly keeps the same voice and URL.
  useEffect(() => {
    const el = audioRef.current;
    if (
      mediaRetryExhausted ||
      !el ||
      !selected?.ready
    ) {
      return;
    }
    const want = srcFor(selected.id);
    const sourceChanged =
      loadedResumeKeyRef.current !== null &&
      loadedResumeKeyRef.current !== selected.resumeKey;
    if (
      el.getAttribute("src") !== want ||
      loadedResumeKeyRef.current !== selected.resumeKey ||
      appliedMediaReloadRef.current !== mediaReload
    ) {
      allowAudioSaveRef.current = false;
      // A retry of the same immutable source keeps the in-memory timestamp.
      // A genuinely new release must never inherit the old asset's position.
      if (sourceChanged) {
        pendingInitialSeekSecondsRef.current = null;
        followCueEnabledRef.current = false;
        setActiveCue(null);
      }
      pendingSeekFractionRef.current = null;
      setPlaying(false);
      setCurrentTime(0);
      setDuration(0);
      loadedResumeKeyRef.current = selected.resumeKey;
      appliedMediaReloadRef.current = mediaReload;
      el.setAttribute("src", want);
      el.load();
    }
  }, [
    selected?.ready,
    selected?.id,
    selected?.resumeKey,
    mediaReload,
    mediaRetryExhausted,
    setActiveCue,
    srcFor,
  ]);

  useEffect(
    () => () => {
      if (mediaRetryTimerRef.current !== null) {
        window.clearTimeout(mediaRetryTimerRef.current);
      }
    },
    [],
  );

  const currentAudioPosition = useCallback(
    (
      requestedTime?: number,
    ): AcademyAudioResumePosition | null => {
      const el = audioRef.current;
      const pendingCheckpoint =
        pendingInitialSeekSecondsRef.current;
      if (
        !resumeEnabled ||
        (!allowAudioSaveRef.current &&
          pendingCheckpoint === null) ||
        !el ||
        !selected?.ready ||
        !selected.resumeKey ||
        loadedResumeKeyRef.current !== selected.resumeKey
      ) {
        return null;
      }
      const authoritativeDuration =
        selected.durationSeconds &&
        Number.isFinite(selected.durationSeconds)
          ? selected.durationSeconds
          : el.duration;
      if (
        !Number.isFinite(authoritativeDuration) ||
        authoritativeDuration <= 0
      ) {
        return null;
      }
      // Media implementations may emit a zero-valued timeupdate while a
      // restored timestamp is still waiting for metadata/canplay. Until that
      // pending seek has actually succeeded, preserve the restored checkpoint
      // instead of letting the transient media time overwrite the shadow with
      // zero during a refresh.
      const checkpointTime =
        !allowAudioSaveRef.current &&
        pendingCheckpoint !== null
          ? pendingCheckpoint
          : Number.isFinite(requestedTime)
            ? requestedTime!
            : pendingCheckpoint ?? el.currentTime;
      return {
        kind: "audio",
        resumeKey: selected.resumeKey,
        voiceId: selected.id,
        positionSeconds: Math.min(
          authoritativeDuration,
          Math.max(0, checkpointTime),
        ),
        durationSeconds: authoritativeDuration,
      };
    },
    [
      resumeEnabled,
      selected?.durationSeconds,
      selected?.id,
      selected?.ready,
      selected?.resumeKey,
    ],
  );

  const persistAudioShadow = useCallback(
    (requestedTime?: number) => {
      if (!resumeShadowScope) return;
      const position = currentAudioPosition(requestedTime);
      if (!position) return;
      writeAcademyAudioResumeShadow(resumeShadowScope, {
        resumeKey: position.resumeKey,
        positionSeconds: position.positionSeconds,
        durationSeconds: position.durationSeconds,
        updatedAt: Date.now(),
      });
    },
    [currentAudioPosition, resumeShadowScope],
  );

  const persistAudioPosition = useCallback(
    (
      requestedTime?: number,
      options?: { keepalive?: boolean },
    ) => {
      const position = currentAudioPosition(requestedTime);
      if (!position) return;
      if (resumeShadowScope) {
        writeAcademyAudioResumeShadow(resumeShadowScope, {
          resumeKey: position.resumeKey,
          positionSeconds: position.positionSeconds,
          durationSeconds: position.durationSeconds,
          updatedAt: Date.now(),
        });
      }
      saveResume(position, options);
    },
    [
      currentAudioPosition,
      resumeShadowScope,
      saveResume,
    ],
  );

  const onLoadedMetadata = () => {
    const el = audioRef.current;
    if (!el) return;
    const mediaDuration =
      Number.isFinite(el.duration) && el.duration > 0
        ? el.duration
        : selected?.durationSeconds ?? 0;
    setDuration(mediaDuration);
    const saved =
      pendingInitialSeekSecondsRef.current;
    if (saved != null && mediaDuration > 0) {
      // Show the saved timestamp as soon as metadata is known. The actual seek
      // waits for canplay (or the user's Play gesture) because older iOS
      // versions can ignore currentTime assignments at loadedmetadata.
      setCurrentTime(
        Math.min(
          Math.max(0, saved),
          Math.max(0, mediaDuration - 0.1),
        ),
      );
    } else if (initialResumeHandledRef.current) {
      // A fresh source with no pending bookmark becomes writable only after its
      // authoritative metadata is available.
      allowAudioSaveRef.current = true;
    }
    el.playbackRate = rateRef.current;
    // Keep the voice's pitch natural at non-1x speeds (Safari needs the
    // webkit-prefixed property below iOS 17.2).
    try {
      el.preservesPitch = true;
      (el as HTMLAudioElement & { webkitPreservesPitch?: boolean }).webkitPreservesPitch = true;
    } catch {
      /* cosmetic */
    }
    if (title && "mediaSession" in navigator) {
      try {
        navigator.mediaSession.metadata = new MediaMetadata({ title, artist: "TenXPros Partner Academy" });
      } catch {
        /* metadata is cosmetic */
      }
    }
  };

  // Apply a pending resume position (after a voice swap) once the new source
  // can actually play. iOS ignores currentTime set at loadedmetadata time, so
  // this runs on canplay AND playing and clears itself on first success.
  const applyPendingSeek = useCallback(() => {
    const el = audioRef.current;
    if (!el) return;
    const initialSeconds =
      pendingInitialSeekSecondsRef.current;
    const mediaDuration =
      Number.isFinite(el.duration) && el.duration > 0
        ? el.duration
        : selected?.durationSeconds ?? 0;
    if (
      initialSeconds != null &&
      mediaDuration > 0 &&
      el.readyState >= HTMLMediaElement.HAVE_METADATA
    ) {
      const target = Math.min(
        Math.max(0, initialSeconds),
        Math.max(0, mediaDuration - 0.1),
      );
      try {
        el.currentTime = target;
      } catch {
        // Keep the pending value. canplay/playing will retry when the media
        // implementation is ready to accept a seek.
        return;
      }
      if (
        Math.abs(el.currentTime - target) > 0.5 &&
        el.readyState < HTMLMediaElement.HAVE_FUTURE_DATA
      ) {
        return;
      }
      pendingInitialSeekSecondsRef.current = null;
      el.playbackRate = rateRef.current;
      setCurrentTime(target);
      allowAudioSaveRef.current = true;
      window.requestAnimationFrame(syncActiveTrackCue);
      return;
    }
    const fraction = pendingSeekFractionRef.current;
    if (fraction == null || mediaDuration <= 0) return;
    pendingSeekFractionRef.current = null;
    el.currentTime = Math.max(0.1, fraction * mediaDuration);
    el.playbackRate = rateRef.current;
    followCueEnabledRef.current = true;
    window.requestAnimationFrame(syncActiveTrackCue);
  }, [selected?.durationSeconds, syncActiveTrackCue]);

  // Bind the persisted timestamp to the exact immutable audio identity before
  // seeking. A release change simply starts at zero; narration never autoplays.
  useEffect(() => {
    if (
      initialResumeHandledRef.current ||
      !selected?.ready ||
      !resumeReconciled
    ) {
      return;
    }
    initialResumeHandledRef.current = true;
    const shadow = resumeShadowScope
      ? readAcademyAudioResumeShadow(resumeShadowScope)
      : null;
    const selectedResume =
      selectFreshestAcademyAudioResume({
        activeResumeKey: selected.resumeKey,
        server: serverResume,
        shadow,
      });
    const saved =
      selectedResume?.checkpoint.positionSeconds ?? null;
    if (
      resumeEnabled &&
      saved != null &&
      Number.isFinite(saved) &&
      saved > 0
    ) {
      pendingInitialSeekSecondsRef.current = saved;
      followCueEnabledRef.current = true;
      const el = audioRef.current;
      if (
        el &&
        el.readyState >=
          HTMLMediaElement.HAVE_METADATA
      ) {
        applyPendingSeek();
      } else {
        setCurrentTime(saved);
      }
    } else {
      followCueEnabledRef.current = false;
      setActiveCue(null);
      if (
        resumeShadowScope &&
        shadow &&
        shadow.resumeKey !== selected.resumeKey
      ) {
        clearAcademyAudioResumeShadow(resumeShadowScope);
      }
      allowAudioSaveRef.current = true;
    }
  }, [
    applyPendingSeek,
    resumeEnabled,
    resumeReconciled,
    resumeShadowScope,
    serverResume,
    setActiveCue,
    selected?.ready,
    selected?.resumeKey,
  ]);

  const toggle = () => {
    const el = audioRef.current;
    if (!el || resumePending) return;
    if (el.paused) {
      followCueEnabledRef.current = true;
      applyPendingSeek();
      el.playbackRate = rateRef.current;
      void el.play().catch(() => {
        // A 404 while regenerating: refresh so the UI shows preparing state.
        void refreshStatus();
      });
    } else {
      el.pause();
    }
  };

  const stop = () => {
    const el = audioRef.current;
    if (!el || resumePending) return;
    followCueEnabledRef.current = false;
    pendingSeekFractionRef.current = null;
    pendingInitialSeekSecondsRef.current = null;
    allowAudioSaveRef.current = true;
    el.pause();
    el.currentTime = 0;
    setCurrentTime(0);
    setFollowAlongPlaying(false);
    setActiveCue(null);
    persistAudioPosition(0);
  };

  const retryStudioAudio = () => {
    mediaRetryAttemptRef.current = 0;
    mediaPlaybackStartedAtRef.current = null;
    setMediaRetryExhausted(false);
    setMediaReload((value) => value + 1);
    void refreshStatus();
  };

  const changeRate = (r: number) => {
    setRate(r);
    rateRef.current = r;
    try {
      window.localStorage.setItem(RATE_PREF_KEY, String(r));
    } catch {
      /* storage unavailable */
    }
    const el = audioRef.current;
    if (el) el.playbackRate = r;
  };

  /**
   * Swap the voice, keeping the position and the playing state. Everything
   * happens synchronously inside the change gesture: set the new source,
   * load, and call play() immediately (it resolves when data arrives), which
   * preserves the playback permission on iOS.
   */
  const changeVoice = (id: string) => {
    setVoiceId(id);
    try {
      window.localStorage.setItem(VOICE_PREF_KEY, id);
    } catch {
      /* storage unavailable */
    }
    const el = audioRef.current;
    const target = status?.voices.find((v) => v.id === id);
    if (!el || !target?.ready) return;
    const wasPlaying = !el.paused && !el.ended;
    pendingSeekFractionRef.current =
      Number.isFinite(el.duration) && el.duration > 0 ? el.currentTime / el.duration : null;
    loadedResumeKeyRef.current = target.resumeKey;
    el.src = srcFor(id);
    el.load();
    if (wasPlaying) {
      void el.play().catch(() => {});
    }
  };

  const seek = (t: number) => {
    const el = audioRef.current;
    if (!el || resumePending) return;
    // A manual seek supersedes any pending voice-swap resume position.
    pendingSeekFractionRef.current = null;
    pendingInitialSeekSecondsRef.current = null;
    allowAudioSaveRef.current = true;
    el.currentTime = t;
    setCurrentTime(t);
    followCueEnabledRef.current = t > 0;
    window.requestAnimationFrame(syncActiveTrackCue);
    persistAudioShadow(t);
  };

  useEffect(() => {
    if (!resumeEnabled) return;
    const flush = () => {
      persistAudioPosition(undefined, {
        keepalive: true,
      });
    };
    const onVisibility = () => {
      if (document.visibilityState === "hidden") flush();
    };
    window.addEventListener("pagehide", flush);
    document.addEventListener(
      "visibilitychange",
      onVisibility,
    );
    return () => {
      window.removeEventListener("pagehide", flush);
      document.removeEventListener(
        "visibilitychange",
        onVisibility,
      );
    };
  }, [persistAudioPosition, resumeEnabled]);

  // Unlike a full page exit, Next.js client navigation does not emit pagehide.
  // Layout cleanup runs while the audio element is still attached, so its exact
  // currentTime is available for the final keepalive checkpoint.
  useLayoutEffect(
    () => () => {
      if (resumeEnabled) {
        persistAudioPosition(undefined, {
          keepalive: true,
        });
      }
    },
    [persistAudioPosition, resumeEnabled],
  );

  if (statusFailed && !status) {
    return (
      <AudioUnavailable
        note="The studio narration could not be reached. Your saved audio position is unchanged."
        onRetry={retryStudioAudio}
      />
    );
  }
  if (!status) {
    return (
      <div
        className="min-h-[7.75rem] rounded-md border border-neutral-200 bg-neutral-50 p-3"
        aria-busy="true"
        aria-label="Preparing lesson audio"
      >
        <span className="text-xs font-semibold uppercase tracking-wide text-slate-500">
          Listen
        </span>
      </div>
    );
  }
  if (
    !status.narration ||
    status.voices.length === 0
  ) {
    return (
      <AudioUnavailable
        note="The studio narration for this lesson is currently unavailable. Your saved audio position is unchanged."
        onRetry={retryStudioAudio}
      />
    );
  }

  if (mediaRetryExhausted) {
    return (
      <AudioUnavailable
        note="The studio narration could not be played after several attempts. Your saved audio position is unchanged."
        onRetry={retryStudioAudio}
      />
    );
  }

  if (!selected?.ready) {
    return (
      <AudioUnavailable
        note="The studio narration for this lesson is being prepared. Your saved audio position is unchanged."
        onRetry={retryStudioAudio}
      />
    );
  }

  return (
    <div className="min-h-[7.75rem] space-y-2 rounded-md border border-neutral-200 bg-neutral-50 p-3">
      <audio
        ref={audioRef}
        preload="metadata"
        onLoadedMetadata={onLoadedMetadata}
        onDurationChange={applyPendingSeek}
        onCanPlay={applyPendingSeek}
        onPlaying={applyPendingSeek}
        onTimeUpdate={() => {
          const el = audioRef.current;
          const time = el?.currentTime ?? 0;
          setCurrentTime(time);
          syncActiveTrackCue();
          const now = Date.now();
          if (
            el &&
            now - lastShadowSaveAtRef.current >= 250
          ) {
            lastShadowSaveAtRef.current = now;
            persistAudioShadow(time);
          }
          if (
            el &&
            !el.paused &&
            mediaPlaybackStartedAtRef.current !== null &&
            now - mediaPlaybackStartedAtRef.current >= 5000
          ) {
            mediaRetryAttemptRef.current = 0;
            mediaPlaybackStartedAtRef.current = null;
          }
          if (
            el &&
            !el.paused &&
            now - lastTimedSaveAtRef.current >= 5000
          ) {
            lastTimedSaveAtRef.current = now;
            persistAudioPosition(time);
          }
        }}
        onPlay={() => {
          followCueEnabledRef.current = true;
          syncActiveTrackCue();
          setPlaying(true);
          setFollowAlongPlaying(true);
          mediaPlaybackStartedAtRef.current = Date.now();
        }}
        onPause={() => {
          setPlaying(false);
          setFollowAlongPlaying(false);
          mediaPlaybackStartedAtRef.current = null;
          persistAudioPosition();
        }}
        onSeeked={() => {
          syncActiveTrackCue();
          persistAudioPosition();
        }}
        onError={(event) => {
          // React observes a failed child <track> through the audio subtree.
          // Timed-text failure disables Follow Along only; it must never
          // trigger retries or remove the independently healthy narration.
          if (event.target !== event.currentTarget) {
            setFollowTrackReady(false);
            setFollowAlongAvailable(false);
            setActiveCue(null);
            return;
          }
          // Refresh status in case the active release changed. If the same
          // ready asset suffered a transient media/network failure, force a
          // bounded-backoff reload as well: a fresh status object alone does
          // not rerun the browser's media load algorithm.
          const el = audioRef.current;
          if (
            el &&
            Number.isFinite(el.currentTime) &&
            el.currentTime > 0
          ) {
            pendingInitialSeekSecondsRef.current =
              el.currentTime;
          }
          setPlaying(false);
          setFollowAlongPlaying(false);
          mediaPlaybackStartedAtRef.current = null;
          void refreshStatus();
          if (mediaRetryTimerRef.current === null) {
            const attempt = mediaRetryAttemptRef.current;
            if (attempt >= MAX_MEDIA_RETRY_ATTEMPTS) {
              persistAudioPosition(undefined, {
                keepalive: true,
              });
              setMediaRetryExhausted(true);
              return;
            }
            mediaRetryAttemptRef.current = attempt + 1;
            const delay = Math.min(
              1000 * 2 ** attempt,
              10_000,
            );
            mediaRetryTimerRef.current =
              window.setTimeout(() => {
                mediaRetryTimerRef.current = null;
                setMediaReload((value) => value + 1);
              }, delay);
          }
        }}
        onEnded={() => {
          const el = audioRef.current;
          followCueEnabledRef.current = false;
          if (el) el.currentTime = 0;
          setPlaying(false);
          setFollowAlongPlaying(false);
          setActiveCue(null);
          mediaPlaybackStartedAtRef.current = null;
          setCurrentTime(0);
          persistAudioPosition(0);
        }}
      >
        {followAlong ? (
          <track
            key={followAlong.manifestHash}
            ref={trackRef}
            kind="metadata"
            src={followAlong.trackUrl}
            default
          />
        ) : null}
      </audio>
      <div className="flex flex-wrap items-center gap-3">
        <span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Listen</span>
        <button
          type="button"
          onClick={toggle}
          disabled={resumePending}
          aria-busy={resumePending}
          className="inline-flex h-9 items-center gap-1.5 rounded-md bg-navy-900 px-3 text-sm font-medium text-white hover:bg-navy-700 disabled:cursor-wait disabled:opacity-60"
        >
          {playing ? <Pause className="h-4 w-4" aria-hidden="true" /> : <Play className="h-4 w-4" aria-hidden="true" />}
          {resumePending
            ? "Restoring"
            : playing
            ? "Pause"
            : currentTime >= 1
              ? "Resume"
              : "Play"}
        </button>
        <button
          type="button"
          onClick={stop}
          disabled={resumePending}
          className="inline-flex h-9 items-center gap-1.5 rounded-md border border-neutral-300 bg-white px-3 text-sm font-medium text-navy-900 hover:bg-neutral-50 disabled:cursor-wait disabled:opacity-60"
        >
          <Square className="h-4 w-4" aria-hidden="true" /> Stop
        </button>
        <label className="flex items-center gap-2 text-xs text-slate-600">
          Speed
          <select
            value={rate}
            onChange={(e) => changeRate(Number(e.target.value))}
            className="h-8 rounded-md border border-neutral-300 bg-white px-2 text-sm"
          >
            {RATES.map((r) => (
              <option key={r} value={r}>{r}x</option>
            ))}
          </select>
        </label>
        {!status.productionVoiceLocked &&
        status.voices.filter((voice) => voice.ready).length >
          1 ? (
          <label className="flex items-center gap-2 text-xs text-slate-600">
            Voice
            <select
              value={selected.id}
              onChange={(e) => changeVoice(e.target.value)}
              className="h-8 max-w-[13rem] rounded-md border border-neutral-300 bg-white px-2 text-sm"
            >
              {status.voices.map((v) => (
                <option key={v.id} value={v.id} disabled={!v.ready}>
                  {v.label}
                  {v.ready ? "" : " (unavailable)"}
                </option>
              ))}
            </select>
          </label>
        ) : null}
        {followAlong && followTrackReady ? (
          <button
            type="button"
            onClick={
              followMode === "suspended"
                ? requestShowActive
                : toggleFollow
            }
            aria-pressed={followMode === "following"}
            className={`inline-flex h-8 items-center rounded-md border px-2.5 text-xs font-semibold transition-colors ${
              followMode === "following"
                ? "border-gold-400 bg-gold-50 text-navy-900"
                : "border-neutral-300 bg-white text-slate-600 hover:bg-neutral-50"
            }`}
          >
            {followMode === "following"
              ? "Following text"
              : followMode === "suspended"
                ? "Resume follow"
                : "Follow audio"}
          </button>
        ) : null}
        {followAlong && followTrackReady && activeCue ? (
          <button
            type="button"
            onClick={requestShowActive}
            className="h-8 text-xs font-semibold text-navy-700 underline decoration-gold-400 underline-offset-4 hover:text-navy-900"
          >
            Show current passage
          </button>
        ) : null}
      </div>
      <div className="min-h-4">
        {currentTime >= 1 && !playing ? (
          <p
            className="text-xs text-slate-500"
            data-testid="academy-audio-resume"
          >
            Ready to continue from {formatTime(currentTime)}.
            Your audio position is saved automatically.
          </p>
        ) : null}
      </div>
      <div className="flex items-center gap-2">
        <span className="w-10 text-right text-xs tabular-nums text-slate-500">{formatTime(currentTime)}</span>
        <input
          type="range"
          min={0}
          max={Math.max(1, Math.floor(duration))}
          step={1}
          value={Math.min(Math.floor(currentTime), Math.floor(duration))}
          onChange={(e) => seek(Number(e.target.value))}
          disabled={resumePending}
          aria-label="Seek"
          aria-valuetext={`${formatTime(currentTime)} of ${formatTime(duration)}`}
          className="h-1.5 flex-1 cursor-pointer accent-navy-900"
        />
        <span className="w-10 text-xs tabular-nums text-slate-500">{formatTime(duration)}</span>
      </div>
    </div>
  );
}
