import type { ModuleSeed } from "./content-types";

export const m02: ModuleSeed = {
  slug: "identity",
  order: 2,
  title: "Your Partner Identity",
  summary: "A partner is a trust builder, not a shortcut seller: the five functions, the four things you protect, and the lines you never cross.",
  passMark: 80,
  examSize: 10,
  lesson: [
    "A partner is a trust builder, not a shortcut seller. Keep that sentence at the center of everything in this module, because the rest is just detail that flows from it.",
    "You can play several roles in a single deal, or just one. The program recognizes five functions, and it pays you for the function you actually performed, not for being nearby when something happened. The five are these. A basic introduction, where you introduce a relevant contact. A qualified origination, where you source an opportunity that can realistically close. A strong origination, where you create a higher quality opportunity, often at scale or with confirmed strategic value. A closing, where you carry the opportunity through to a signed, binding agreement. And delivery or coaching, where you help deliver, coach, or support the offering when you are approved to do so. You will see exactly how each one pays in the Rules module. For now, learn the names and what each means, because you will describe your own role honestly when you register a deal.",
    "The mindset underneath all five is simple and it protects you as much as it protects the company. A partner protects the brand. A partner protects the prospect. A partner protects the standard. And a partner protects their own right to earn by following the process. Those four hold together. Drop one and the others get weaker. Protect the prospect, for instance, and you protect the brand at the same time, because an honest introduction is what makes the brand trustworthy in the first place.",
    "Now the part that matters most for keeping you safe and keeping the program clean: the things a partner must never do. Read these slowly, because crossing any of them can end a partnership and, in some cases, expose you personally.",
    "Never promise certification. The credential is earned through a reviewed dossier, and no one can guarantee the outcome of a review. Never promise income, employment, promotion, leads, or business results. You are introducing a learning program, not selling a job or a raise. Never imply TenXPros is a university degree or an accredited academic program, because it is a private professional certification and saying otherwise is a false claim. Never ask for or accept payment outside official channels, and never use messaging that has not been approved. Never contact a prospect using the TenXPros name before you have completed the Activation Gate. Never use spam, scraped lists, or bought lists. Never submit, or encourage anyone to submit, confidential client, employer, patient, or regulated data without the rights and safeguards to handle it. And never claim exclusive authority over an industry, a country, or a territory unless it is confirmed in writing on the Partner Panel.",
    "Those are not arbitrary restrictions. Each one exists because breaking it damages a real person or a real obligation. Promise a job and you set up a participant for a betrayal that lands on your name. Imply accreditation and you mislead someone making a serious decision. Mishandle regulated data and you create legal exposure for the participant, the company, and yourself. The rule protects the people in the room.",
    "Here is how to think on your feet in the field. Before you say a sentence to a prospect, run it through a quick test. Is it true. Can I back it up. Does it promise an outcome I cannot control. Does it route money or data the wrong way. If a sentence fails any of those, do not say it. If you are not sure, treat that doubt as a no until you confirm on the Partner Panel.",
    "A short example of the judgment you will use constantly. Saying, this is a strong fit because you already have deep expertise and one real problem worth solving, is approved. It qualifies on genuine readiness, which is exactly your job. Saying, join and you will be certified automatically after twelve weeks, is prohibited, because certification is earned through review, not attendance, and you cannot promise it. The difference between those two sentences is the whole module in miniature. One protects the standard and the prospect. The other quietly breaks both.",
    "So your identity, in one breath: you are the person who recognizes the right professional, tells them the truth, registers your real role honestly, and protects the standard even when bending it would be easier. That is what earns you the long term trust that makes this worth doing.",
  ].join("\n\n"),
  exercises: [
    {
      stem: "How many functions can a partner perform in a single deal?",
      options: ["Only one, ever", "One or several", "Exactly two", "All five are required every time"],
      correct: 1,
      explanation: "The lesson says a partner can play several roles in one deal or just one. It is not capped at one or two, and performing all five is never required.",
    },
    {
      stem: "Which of these is the function called strong origination?",
      options: ["Introducing a relevant contact", "Creating a higher quality opportunity, often at scale or with confirmed strategic value", "Carrying a deal to a signed agreement", "Coaching a participant after approval"],
      correct: 1,
      explanation: "Strong origination is the higher quality, often larger or strategically confirmed opportunity. The others describe introduction, closing, and delivery or coaching.",
    },
    {
      stem: "What are the four things a partner protects?",
      options: ["Brand, prospect, standard, and their own right to earn", "Price, discount, speed, and volume", "Only the brand and the company", "The partner's commission above all else"],
      correct: 0,
      explanation: "The four are brand, prospect, standard, and the partner's own right to earn by following the process. The other options miss or distort the set.",
    },
    {
      stem: "Which action is prohibited for a partner?",
      options: ["Qualifying a prospect on genuine readiness", "Promising a participant a promotion within a year", "Using approved messaging", "Registering a deal honestly"],
      correct: 1,
      explanation: "Promising employment, promotion, income, or results is prohibited. The other three are exactly what a partner should do.",
    },
    {
      stem: "A prospect offers to pay you directly so enrollment moves faster. What do you do?",
      options: ["Accept it to speed things up", "Refuse, because payment must go through official channels", "Accept it only for the first payment", "Ask for half now and half later"],
      correct: 1,
      explanation: "Taking payment outside official channels is prohibited without exception. Any version of accepting direct payment breaks the rule.",
    },
    {
      stem: "Before saying a sentence to a prospect, which question is part of the quick test?",
      options: ["Will this sentence impress them regardless of truth", "Does it promise an outcome I cannot control", "Can I make it sound more urgent", "Will it hide the review standard"],
      correct: 1,
      explanation: "The test asks whether a claim is true, backable, and free of uncontrollable promises or wrong money and data routing. Impressing, adding false urgency, or hiding the bar are not part of it.",
    },
  ],
  exam: [
    {
      stem: "The single sentence at the center of the partner identity is which of these?",
      options: ["A partner is a volume reseller", "A partner is a trust builder, not a shortcut seller", "A partner is a recruiter", "A partner is a discount broker"],
      correct: 1,
      explanation: "The module centers on trust builder, not shortcut seller. The other identities are explicitly not what a partner is.",
    },
    {
      stem: "A partner is paid for what, exactly?",
      options: ["Being present when a deal happens", "The function they actually performed", "The largest possible role regardless of contribution", "Any role they claim verbally"],
      correct: 1,
      explanation: "Pay follows the function actually performed, not proximity, not an inflated claim, not an unverified verbal role.",
    },
    {
      stem: "Which pairing of function and meaning is correct?",
      options: ["Basic introduction means closing a signed agreement", "Closing means introducing a contact", "Qualified origination means sourcing an opportunity that can realistically close", "Delivery means claiming a territory"],
      correct: 2,
      explanation: "Qualified origination is sourcing a realistically closable opportunity. The other pairings swap the meanings.",
    },
    {
      stem: "Why does protecting the prospect also protect the brand?",
      options: ["Because an honest introduction is what makes the brand trustworthy", "Because the brand does not depend on prospects", "Because protecting the prospect lets you skip the standard", "Because it increases the commission cap"],
      correct: 0,
      explanation: "Honest treatment of prospects is what builds brand trust, so the two reinforce each other. The other options are false.",
    },
    {
      stem: "Which of the following is a prohibited claim?",
      options: ["The credential is earned through a reviewed dossier", "TenXPros is a selective twelve week certification", "TenXPros is basically an accredited university qualification", "Participants bring one real problem to the program"],
      correct: 2,
      explanation: "Implying accreditation or a degree is prohibited and false. The other statements are accurate descriptions.",
    },
    {
      stem: "When may a partner contact a prospect using the TenXPros name?",
      options: ["Immediately after signing up", "Only after completing the Activation Gate", "Whenever they feel ready", "After their first commission"],
      correct: 1,
      explanation: "Outreach using the name is allowed only after the Activation Gate is complete and confirmed, not on signup, feel, or first commission.",
    },
    {
      stem: "A partner wants to move quickly and considers using a list of contacts they purchased. What is correct?",
      options: ["Buying lists is fine if the leads are relevant", "Bought, scraped, and spam lists are prohibited", "Scraped lists are allowed but bought lists are not", "It is allowed during the pilot only"],
      correct: 1,
      explanation: "Bought lists, scraped lists, and spam are all prohibited, with no relevance, type, or timing exception.",
    },
    {
      stem: "Why is mishandling regulated or confidential data treated so seriously?",
      options: ["It only affects the company", "It creates legal exposure for the participant, the company, and the partner", "It is a minor formatting issue", "It is allowed if the participant agrees verbally"],
      correct: 1,
      explanation: "The exposure lands on everyone involved, which is why rights and safeguards are required. It is not minor and not cured by a verbal agreement.",
    },
    {
      stem: "Which sentence is approved for a partner to say?",
      options: ["You will be certified automatically after twelve weeks", "This is a strong fit because you already have deep expertise and one real problem worth solving", "Finish the program and your income will rise", "I can guarantee you pass the review"],
      correct: 1,
      explanation: "Only this qualifies honestly on readiness. The others promise certification, income, or a guaranteed review outcome.",
    },
    {
      stem: "A partner may claim exclusive authority over an industry or territory in which case?",
      options: ["Whenever they have the most clients there", "Only when it is confirmed in writing on the Partner Panel", "After ninety days automatically", "If a verbal agreement was made"],
      correct: 1,
      explanation: "Exclusivity exists only when confirmed in writing on the Panel, not by client count, time, or a verbal deal.",
    },
    {
      stem: "A sentence fails the quick test if it does which of these?",
      options: ["States a fact you can back up", "Promises an outcome you cannot control", "Describes the four phases accurately", "Qualifies the prospect honestly"],
      correct: 1,
      explanation: "Promising an uncontrollable outcome fails the test. Backable facts, accurate descriptions, and honest qualification all pass.",
    },
    {
      stem: "In one breath, the partner identity is best summarized as which of these?",
      options: ["Recognize the right professional, tell the truth, register your real role, and protect the standard", "Close as many deals as possible by any means", "Promise outcomes that make people feel safe", "Move money and data quickly to speed enrollment"],
      correct: 0,
      explanation: "The summary is honest recognition, truth, accurate role registration, and protecting the standard. The others describe behavior the module prohibits.",
    },
  ],
};
