import type { Metadata } from "next";
import { headers } from "next/headers";
import { SITE_URL } from "@/lib/seo";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "TenXPros",
    template: "%s | TenXPros",
  },
  description:
    "A selective 100-day AI adoption journey for experienced professionals, with a 12-week guided learning path and a defensible Living AI Solution Dossier.",
  robots: { index: true, follow: true },
  other: {
    cryptomus: "e50d84e2",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Reading request headers opts every HTML route into per-request rendering,
  // allowing Next.js to apply the nonce generated by middleware to its scripts.
  headers();

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
